version: '3.9'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v20.2.8
    command: start-single-node --insecure
    ports:
    - "26257:26257"
    - "8080:8080"
    networks:
      default:
        aliases:
        - auth-server-cockroach-public
  db-init:
    image: db-init
    volumes:
    - "./migrations/init-conf.yaml:/config.yaml"
    depends_on:
    - cockroachdb
  migrations:
    image: docker.io/flyway/flyway:7
    command: [ migrate ]
    volumes:
    - "./migrations/flyway.conf:/flyway/conf/flyway.conf"
    - "./migrations/sql:/flyway/sql"
    depends_on:
    - db-init
  login:
    image: auth-server/login
    depends_on:
    - migrations
    hostname: login.int-auth-server.svc.cluster.local
    environment:
      PONGLE_SERVER_PORT: "80"
  get:
    image: auth-server/users-get
    depends_on:
    - migrations
    hostname: users-get.int-auth-server.svc.cluster.local
    environment:
      PONGLE_SERVER_PORT: "80"
  post:
    image: auth-server/users-post
    depends_on:
    - migrations
    hostname: users-post.int-auth-server.svc.cluster.local
    environment:
      PONGLE_SERVER_PORT: "80"
  put:
    image: auth-server/users-put
    depends_on:
    - migrations
    hostname: users-put.int-auth-server.svc.cluster.local
    environment:
      PONGLE_SERVER_PORT: "80"
  list:
    image: auth-server/users-list
    depends_on:
    - migrations
    hostname: users-list.int-auth-server.svc.cluster.local
    environment:
      PONGLE_SERVER_PORT: "80"
  delete:
    image: auth-server/users-delete
    depends_on:
    - migrations
    hostname: users-delete.int-auth-server.svc.cluster.local
    environment:
      PONGLE_SERVER_PORT: "80"