version: '3.9'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v20.2.8
    command: start-single-node --insecure
    ports:
    - "26257:26257"
    - "8080:8080"
    hostname: auth-server-cockroach-public
  db-init:
    image: db-init
    volumes:
    - "./migrations/init-conf.yaml:/config.yaml"
    depends_on:
    - cockroachdb
  migrations:
    image: docker.io/flyway/flyway:7
    command: [ migrate ]
    volumes:
    - "./migrations/flyway.conf:/flyway/conf/flyway.conf"
    - "./migrations/sql:/flyway/sql"
    depends_on:
    - db-init