FROM ../../libraries/images/golang+image

deps:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY internal ./internal
  COPY cmd ./cmd

build:
  FROM +deps

  ARG APPLICATION_NAME

  RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ${APPLICATION_NAME} ./cmd/${APPLICATION_NAME}/${APPLICATION_NAME}.go

  SAVE ARTIFACT ${APPLICATION_NAME}

docker:
  FROM scratch

  ARG APPLICATION_NAME

  COPY --build-arg APPLICATION_NAME="$APPLICATION_NAME" +build/${APPLICATION_NAME} /go/bin/app
  ENTRYPOINT [ "/go/bin/app" ]

  SAVE IMAGE auth-server/${APPLICATION_NAME}

all:
  BUILD --build-arg APPLICATION_NAME=login +docker
  BUILD --build-arg APPLICATION_NAME=users-delete +docker
  BUILD --build-arg APPLICATION_NAME=users-get +docker
  BUILD --build-arg APPLICATION_NAME=users-list +docker
  BUILD --build-arg APPLICATION_NAME=users-post +docker
  BUILD --build-arg APPLICATION_NAME=users-put +docker

test:
  FROM +deps
  COPY docker-compose.yaml docker-compose.yaml

  WITH DOCKER --compose docker-compose.yaml
    RUN CGO_ENABLED=0 \
      GOOS=linux \
      GOARCH=amd64 \
      DB_HOST=localhost \
      DB_USER=root \
      go test ./cmd/...
  END
