FROM golang:1.16

WORKDIR /src

deps:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY internal ./internal
  COPY cmd ./cmd

build:
  FROM +deps

  ARG APPLICATION_NAME

  RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ${APPLICATION_NAME} ./cmd/${APPLICATION_NAME}/${APPLICATION_NAME}.go

  SAVE ARTIFACT ${APPLICATION_NAME}

docker:
  FROM scratch

  ARG APPLICATION_NAME

  COPY --build-arg APPLICATION_NAME="$APPLICATION_NAME" +build/${APPLICATION_NAME} /go/bin/app
  ENTRYPOINT [ "/go/bin/app" ]

  SAVE IMAGE auth-server/${APPLICATION_NAME}

test:
  FROM +deps

  ARG APPLICATION_NAME

  RUN --no-cache --mount=type=cache,target=/root/.cache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 DB_HOST=172.17.0.1 go test ./cmd/${APPLICATION_NAME}

test-all:
  FROM +deps
  RUN --no-cache --mount=type=cache,target=/root/.cache \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    DB_HOST=172.17.0.1 \
    DB_USER=root \
    go test ./cmd/...

test-build:
  FROM +deps

  ENTRYPOINT [ "go" ]
  CMD [ "test", "./cmd/..." ]

  ENV CGO_ENABLED=0
  ENV GOOS=linux
  ENV GOARCH=amd64
  ENV DB_USER=root

  SAVE IMAGE auth-server/tests

test-docker:
  FROM scratch

  COPY +test-build /go/bin/tests
  ENTRYPOINT [ "/go/bin/tests" ]

  SAVE IMAGE auth-server/tests

test-run:
  FROM earthly/dind:alpine

  COPY docker-compose.yaml ./
  WITH DOCKER --compose docker-compose.yaml \
      --load auth-server/tests=+test-build \
      --pull cockroachdb/cockroach:v20.2.8
    RUN docker run \
          --network default_default \
          -e DB_HOST=cockroachdb \
          auth-server/tests
  END 

database:
  LOCALLY
    RUN docker-compose up -d

clean:
  LOCALLY
    RUN docker-compose down