FROM golang:1.16

WORKDIR /src

deps:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY main.go ./main.go
  COPY internal ./internal

build:
  FROM +deps

  RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o auth-server-mock main.go

  SAVE ARTIFACT auth-server-mock

docker:
  FROM scratch

  ARG APPLICATION_NAME

  COPY +build/auth-server-mock /go/bin/app
  ENTRYPOINT [ "/go/bin/app" ]

  SAVE IMAGE auth-server-mock

test:
  FROM +deps
  RUN --no-cache --mount=type=cache,target=/root/.cache \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    go test ./...