FROM ../../../libraries/images/node+image
WORKDIR /src

docker:
  COPY ../../../libraries/node/eslint-config-ponglehub+publish/marker /markers/1
  COPY ../../../libraries/node/async+publish/marker /markers/2

  COPY package*.json ./
  RUN npm install

  COPY . .

  ENTRYPOINT [ "npm" ]
  CMD [ "run", "int-test-watch" ]

  SAVE IMAGE auth-operator-tests

lint:
  FROM +deps
  RUN npm run lint