FROM golang:1.16
WORKDIR /src

image:
    RUN apt-get remove -y docker docker-engine docker.io containerd runc || true && \
        apt-get update && \
        apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common && \
        curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add - && \
        add-apt-repository \
            "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian \
            $(lsb_release -cs) \
            stable" && \
        apt-get update && \
        apt-get install -y docker-ce docker-ce-cli containerd.io && \
        curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
        chmod +x /usr/local/bin/docker-compose
    
    RUN update-alternatives --set iptables /usr/sbin/iptables-legacy
    RUN update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
