FROM node:14.17.1-alpine
WORKDIR /src

npmrc:
  RUN apk add expect
  COPY login.sh login.sh
  RUN ./login.sh
  SAVE ARTIFACT /root/.npmrc npmrc

image:
  RUN apk add jq

  COPY +npmrc/npmrc /root/.npmrc
  COPY patch.sh /usr/local/bin/patch