clean:
    rm -rf ./dist
    mkdir -p dist/compiled
    mkdir -p dist/js

deps:
    npm install

build: deps
    npm run build

watch: deps
    npm run watch

wasm:
    mkdir -p dist/compiled
    tinygo build -o dist/compiled/naughts-and-crosses.wasm -target wasm ./wasm/main.go

image IMAGE_TAG: build
    DOCKER_BUILDKIT=1 docker build \
        -f ../../docker/nginx.Dockerfile \
        -t {{IMAGE_TAG}} \
        ./dist
