clean:
    rm -rf ./dist
    mkdir -p dist/compiled
    mkdir -p dist/js

deps:
    npm install

build: deps
    npm run build

watch: deps
    npm run watch

image IMAGE_TAG: build
    DOCKER_BUILDKIT=1 docker build \
        -f ../../docker/nginx.Dockerfile \
        -t {{IMAGE_TAG}} \
        ./dist
