{
 "title": "Custom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"local-dev-control-plane\"}) / sum(machine_memory_bytes) * 100",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=\"local-dev-control-plane\"}[5m])) / sum(machine_cpu_cores{kubernetes_io_hostname=\"local-dev-control-plane\"}) * 100",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}