{{ $functions := .Values.functions }}
{{ $root := . }}

{{- range $name, $function := $functions }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    tier: {{ default "private" $function.tier }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: {{ $function.image }}
          {{- if $function.env }}
          env:
          {{- range $key, $value := $function.env }}
          - name: {{ $key }}
            value: {{ tpl $value $root }}
          {{- end }}
          {{- end }}
{{- end }}