{{- $root := . }}
{{- range $name, $server := .Values.servers }}
{{- if $server.enabled }}
{{- if $server.db }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}-cdb
rules:
- apiGroups:
  - certificates.k8s.io 
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-cdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}-cdb
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}-cdb
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-cdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}-cdb
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ required "must enter a name property!" $name }}
  name: {{ required "must enter a name property!" $name }}
spec:
  replicas: {{ $server.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ required "must enter a name property!" $name }}
      {{- if $server.annotations }}
      annotations:
      {{- range $key, $value := $server.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ $name }}
      {{- if (or $server.initContainers $server.db) }}
      initContainers:
      {{- end }}
      {{- if $server.initContainers }}
      {{- range $key, $container := $server.initContainers }}
      - name: {{ $container.name }}
        image: {{ required "must enter an image property!" $container.image}}
        imagePullPolicy: {{ $container.pullPolicy | default "Always" }}
        {{- if $container.env }}
        env:
        {{- range $name, $value := $container.env }}
        - name: {{ $name }}
          value: {{ tpl $value $root }}
        {{- end }}
        {{- end }}
        resources:
        {{- if $server.resources }}
          {{- toYaml $server.resources | nindent 10 }}
        {{- else }}
          requests:
            memory: 32Mi
            cpu: 0.1
          limits:
            memory: 32Mi
            cpu: 0.1
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      {{- end }}
      {{- end }}
      {{- if  $server.db }}
      - name: init-certs
        command:
        - /bin/ash
        - -ecx
        - /request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs/ -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt -type=node -addresses=localhost,127.0.0.1,$(hostname -f),$(hostname -f|cut -f 1-2 -d '.'),cockroachdb-public,cockroachdb-public.$(hostname -f|cut -f 3- -d '.')
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: cockroachdb/cockroach-k8s-request-cert:0.4
        imagePullPolicy: IfNotPresent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cockroach-certs/
          name: certs
      {{- end }}
      containers:
      - name: server
        image: {{ required "must enter an image property!" $server.image}}
        imagePullPolicy: {{ $server.pullPolicy | default "Always" }}
        {{- if $server.command }}
        command:
          {{- range $server.command }}
        - {{ . }}
          {{- end }}
        {{- end }}
        {{- if $server.args }}
        args:
          {{- range $server.args }}
        - {{ . | quote }}
          {{- end }}
        {{- end }}
        {{- if (or $server.env $server.db) }}
        env:
        {{- end }}
        {{- if $server.env }}
        {{- range $key, $value := $server.env }}
        - name: {{ $key }}
          value: {{ tpl $value $root }}
        {{- end }}
        {{- end }}
        {{- if $server.db }}
        - name: POSTGRES_HOST
          value: cockroachdb
        - name: POSTGRES_PORT
          value: "26257"
        - name: POSTGRES_USER
          value: {{ $server.db.user }}
        - name: POSTGRES_PASS
          value: test_password
        - name: POSTGRES_CERTS
          value: /certs
        - name: POSTGRES_NAME
          value: {{ $server.db.database }}
        {{- end }}
        resources:
        {{- if $server.resources }}
          {{- toYaml $server.resources | nindent 10 }}
        {{- else }}
          requests:
            memory: 32Mi
            cpu: 0.1
          limits:
            memory: 32Mi
            cpu: 0.1
        {{- end }}
        {{- if $server.db }}
        volumeMounts:
        - name: certs
          mountPath: /certs
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      {{- if $server.db }}
      volumes:
      - name: certs
        emptyDir: {}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $name }}
  name: {{ $name }}
spec:
  ports:
  {{- if $server.ports }}
  {{- range $_, $port := $server.ports }}
  - name: {{ $port | quote }}
    port: {{ $port }}
    protocol: TCP
    targetPort: {{ $port }}
  {{- end }}
  {{- else }}
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ $server.port | default 80 }}
  {{- end }}
  selector:
    app: {{ $name }}
  type: ClusterIP
{{- if not (empty $server.host) }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
{{- if not $server.noAuth }}
    ingress.kubernetes.io/auth-url: http://gatekeeper.ponglehub.svc.cluster.local/loggedIn
    ingress.kubernetes.io/auth-type: forward
{{- end }}
  labels:
    app: {{ $name }}
  name: {{ $name }}
spec:
  rules:
  - host: {{ required "must provide a host!" $server.host }}
    http:
      paths:
      - backend:
          serviceName: {{ $name }}
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ $server.host }}
    secretName: ssl-secret
{{- end }}
{{- if not (empty $server.rbac) }}
{{- if $server.rbac.clusterWide }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
rules:
- apiGroups:
  {{- range $server.rbac.apiGroups }}
  - {{ . }}
  {{- end }}
  resources:
  {{- range $server.rbac.resources }}
  - {{ . }}
  {{- end }}
  verbs:
  {{- range $server.rbac.verbs }}
  - {{ . }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
rules:
- apiGroups:
  {{- range $server.rbac.apiGroups }}
  - {{ . }}
  {{- end }}
  resources:
  {{- range $server.rbac.resources }}
  - {{ . }}
  {{- end }}
  verbs:
  {{- range $server.rbac.verbs }}
  - {{ . }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
