{{- $root := . }}
{{- range $name, $storage := .Values.cockroach }}
apiVersion: ponglehub.co.uk/v1alpha1
kind: CockroachDB
metadata:
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  storage: {{ default "512Mi" $storage }}
{{- end }}