{{ $root := . }}
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ $name }}
data:
    {{- range $key, $value := $secret }}
    {{ $key }}: {{ b64enc $value }}
    {{- end }}
{{- end }}