[package]
name = "mock"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
rocket = { version="0.5.0-rc.1", features=["json"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }