{{- $db := .Values.migrations.db -}}
{{- range .Values.migrations.sets }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .database }}-migration
data:
  flyway.conf: |
    flyway.url=jdbc:postgresql://{{ $db.host }}:{{ $db.port }}/{{ .database }}
    flyway.user={{ .user }}
{{- end }}