FROM ../../libraries/images/helm+image

WORKDIR /src

deps:
  RUN helm repo add local http://helm.ponglehub.co.uk:5002

  DEPENDS ON ../../libraries/helm/common-templates+publish

  COPY Chart* ./
  RUN helm dep update

  COPY values.yaml values.yaml
  COPY templates templates

publish:
  FROM +deps
  RUN helm push . local --force