FROM ../../libraries/images/helm+image

WORKDIR /src

deps:
  RUN helm repo add local http://helm.ponglehub.co.uk:5002

  COPY ../../libraries/helm/common-templates+publish/marker /markers/1

  COPY Chart* ./
  RUN helm repo update && helm dep update

  COPY values.yaml values.yaml
  COPY --dir templates templates

lint:
  FROM +deps

  COPY lint-values.yaml lint-values.yaml
  RUN helm lint --values lint-values.yaml

publish:
  FROM +deps
  BUILD +lint  

  RUN patch test-chart
  SAVE ARTIFACT marker