FROM ../../../libraries/images/node+image
WORKDIR /src

deps:
  COPY ../../../libraries/node/eslint-config-ponglehub+publish/marker /markers/1
  COPY ../../../libraries/node/async+publish/marker /markers/2

  COPY package*.json ./
  RUN npm install

  COPY --dir tests helpers .

lint:
  FROM +deps
  RUN npm run lint

docker:
  FROM +deps

  ENTRYPOINT [ "npm" ]
  CMD [ "run", "int-test-watch" ]

  SAVE IMAGE auth-server-tests

docker-ci:
  FROM +deps

  ENTRYPOINT [ "npm" ]
  CMD [ "run", "int-test" ]

  SAVE IMAGE auth-server-tests-ci

all:
  BUILD +lint
  BUILD +docker