apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventtriggers.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                filters:
                  type: array
                  items:
                    type: string
                url:
                  type: string
              required: [ filters, url ]
  scope: Namespaced
  names:
    plural: eventtriggers
    singular: eventtrigger
    kind: EventTrigger
    shortNames:
    - et