apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authusers.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required: [ name, email, password ]
            status:
              type: object
              properties:
                verified:
                  type: boolean
  scope: Namespaced
  names:
    plural: authusers
    singular: authuser
    kind: AuthUser