FROM ../../../libraries/images/node+image

deps:
    COPY ../../../libraries/node/eslint-config-ponglehub+publish/marker /markers/1
    COPY ../../../libraries/node/async+publish/marker /markers/2

    COPY package*.json ./
    RUN npm ci

    COPY ./.eslintrc ./.eslintrc
    COPY ./src ./src

image:
    FROM +deps

    ENTRYPOINT [ "npm" ]
    CMD [ "start" ]

    SAVE IMAGE mock