FROM ../../images/helm+image

WORKDIR /src

deps:
  RUN helm repo add local http://helm.ponglehub.co.uk:5002

  COPY Chart* ./
  RUN helm dep update

  COPY values.yaml values.yaml
  COPY templates templates

publish:
  FROM +deps
  RUN patch common-templates
  SAVE ARTIFACT marker