apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cockroachclients.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                database:
                  type: string
                secret:
                  type: string
              required: [ database, secret ]
  scope: Namespaced
  names:
    plural: cockroachclients
    singular: cockroachclient
    kind: CockroachClient