apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: keycloak.enabled
  name: keycloak
  repository: https://codecentric.github.io/helm-charts
  version: '*'
- name: common-templates
  repository: '@local'
  version: '*'
description: A Helm chart for Kubernetes
name: ponglehub
type: application
version: 1.0.6
