keycloak:
  enabled: true
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_LOGLEVEL
      value: "DEBUG"
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      value: "admin"
jobs:
- name: keycloak-init
  image: keycloak-init