global:
  auth:
    # user:
    # password:
  smtp:
    # email:
    # password:
    # host:
    # port:
    # from:
  ssl:
    # key:
    # crt:

seed:
  # name:
  # email:

migrations:
  baseImage: db-init
  flywayImage: docker.io/flyway/flyway:7
  db:
    host: cockroach-cockroachdb-public.infra.svc.cluster.local
    port: 26257
  sets:
  - user: authserver
    database: auth
    image: auth-migrations

jobs: []

servers:
- name: game-state
  image: game-state
  host: game-state.ponglehub.co.uk
- name: auth-server
  image: auth-server
  env:
    RUST_LOG: info
- name: gatekeeper
  image: gatekeeper
  env:
    RUST_LOG: info
- name: doorman
  image: doorman
  host: auth.ponglehub.co.uk
  noAuth: true
  env:
    RUST_LOG: info
- name: auth-controller
  image: auth-controller
  env:
    RUST_LOG: info,hyper=info
  rbac:
    apiGroups:
    - auth.ponglehub.co.uk
    resources:
    - clients
    - userseeds
    - userseeds/status
    verbs:
    - list
    - watch
    - patch

static:
- name: landing-page
  image: landing-page
  host: games.ponglehub.co.uk
