global:
  auth:
    # user:
    # password:
  smtp:
    # email:
    # password:
    # host:
    # port:
    # from:
  ssl:
    # key:
    # crt:

jobs: []

servers:
- name: auth-server
  image: auth-server

static:
- name: landing-page
  image: landing-page
  host: games.ponglehub.co.uk
