global:
  auth:
    # user:
    # password:
  smtp:
    # email:
    # password:
    # host:
    # port:
    # from:
  ssl:
    # key:
    # crt:

migrations:
  baseImage: db-init
  db:
    host: cockroach-cockroachdb-public.infra.svc.cluster.local
    port: 26257
  sets:
  - user: authserver
    database: auth
    image: auth-migrations

jobs: []

servers:
- name: auth-server
  image: auth-server
  env:
    ROCKET_PORT: "80"
    ROCKET_ADDRESS: "0.0.0.0"
    ROCKET_DATABASES: '{auth={url="postgresql://authserver@cockroach-cockroachdb-public.infra.svc.cluster.local:26257/auth?sslmode=disable"}}'
- name: gatekeeper
  image: gatekeeper
  host: auth.ponglehub.co.uk
  env:
    ROCKET_PORT: "80"
    ROCKET_ADDRESS: "0.0.0.0"
- name: auth-controller
  image: auth-controller
  command: [ "/bin/sh" ]
  args:
  - -c
  - while true; do echo "tick"; sleep 5; done;
  env:
    RUST_LOG: trace,kube=trace
static:
- name: landing-page
  image: landing-page
  host: games.ponglehub.co.uk
