FROM ../../images/node+image

deps:
  COPY ../eslint-config-ponglehub+publish/marker /markers/1

  COPY package*.json ./
  RUN npm ci

  COPY ./.eslintrc ./.eslintrc
  COPY ./lib ./lib

lint:
  FROM +deps
  RUN npm run lint

unit:
  FROM +deps
  RUN npm run test

publish:
  FROM +deps
  RUN patch
  SAVE ARTIFACT marker

all:
  BUILD +lint
  BUILD +unit
  BUILD +publish