{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.existingSecret }}
data:
  admin-user: {{ .Values.secrets.admin.username | b64enc }}
  admin-password: {{ .Values.secrets.admin.password | b64enc }}
{{- end -}}