FROM ../../images/node+image

deps:
  COPY package*.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./lib ./lib

publish:
  FROM +deps
  RUN patch
  SAVE ARTIFACT marker

all:
  BUILD +publish