FROM node:10.15.3-alpine
WORKDIR /src

deps:
  RUN --secret NPMRC_FILE=+secrets/NPMRC_FILE printf "$NPMRC_FILE" > ~/.npmrc
  COPY package*.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./lib ./lib

publish:
  FROM +deps

  RUN npm run patch
  RUN npm publish

all:
  BUILD +publish