clean:
    rm -rf ./dist
    mkdir -p dist/compiled
    mkdir -p dist/js

deps:
    npm install

build: deps
    npm run build

watch: deps
    npm run watch

image IMAGE_TAG: build
    just ../../libraries/images/nginx/image
    DOCKER_BUILDKIT=1 docker build \
        -f ../../docker/nginx.Dockerfile \
        -t {{IMAGE_TAG}} \
        ./dist

start:
    just image landing-page
    -docker stop landing-page
    docker run --name landing-page --hostname landing-page --rm -it -d -v $(pwd)/dist:/usr/share/nginx/html -p 7001:80 landing-page

stop:
    -docker stop landing-page