clean:
    rm -rf ./dist
    mkdir -p dist/compiled
    mkdir -p dist/js

build: statics web-components

deps:
    npm install

watch: deps
    npm run watch

statics:
    cp -r ./static/ ./dist/

web-components: deps
    npm run build

image IMAGE_TAG: build
    just ../../libraries/images/nginx/image
    DOCKER_BUILDKIT=1 docker build \
        -f ../../docker/nginx.Dockerfile \
        -t {{IMAGE_TAG}} \
        ./dist

start:
    just image landing-page
    -docker stop landing-page
    docker run --name landing-page --hostname landing-page --rm -it -d -v $(pwd)/dist:/usr/share/nginx/html -p 7001:80 landing-page

stop:
    -docker stop landing-page