version: '3'
services:
  server:
    image: "rancher/k3s:latest"
    command: [ server, --no-deploy=traefik ]
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=83jd2938dj2389d
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    volumes:
    - ./registries.yaml:/etc/rancher/k3s/registries.yaml
    # This is just so that we get the kubeconfig file out
    - ${OUTPUT_DIR:?err}:/output
    ports:
    - 6443:6443

  # agent:
  #   image: "rancher/k3s:${K3S_VERSION:-latest}"
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   volumes:
  #   - ./registries.yaml:/etc/rancher/k3s/registries.yaml
  #   privileged: true
  #   environment:
  #   - K3S_URL=https://server:6443
  #   - K3S_TOKEN=83jd2938dj2389d

  registry:
    image: registry:2
    ports:
    - 5000:5000
