image:
    FROM earthly/dind:alpine

    COPY wait-for-cluster /usr/local/bin/wait-for-cluster
    COPY cluster-compose.yaml /k3s/cluster-compose.yaml
    COPY registries.yaml /k3s/registries.yaml

    RUN apk add curl \
        && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
        && chmod +x ./kubectl \
        && mv ./kubectl /usr/local/bin \
        && chmod +x /usr/local/bin/wait-for-cluster

    WORKDIR /src

    ENV OUTPUT_DIR=/scratch
    ENV KUBECONFIG=/scratch/kubeconfig.yaml