#!/bin/sh

echo "waiting for kubeconfig file"
while [ ! -f $KUBECONFIG ]; do
    echo "tick..."
    sleep 0.5
done

echo "waiting for pods to exist"
lines="$(kubectl get pods -A -o json | jq '.items[].metadata.name' | wc -l)"
while [ "$lines" = "0" ]; do
    echo "- waiting..."
    sleep 0.5
    lines="$(kubectl get pods -A -o json | jq '.items[].metadata.name' | wc -l)"
done

echo "waiting for pods to be ready"
lines="$(kubectl get pods -n kube-system -o json | jq '.items[].status.phase | select(. != "Running")' | wc -l)"
while [ "$lines" != "0" ]; do
    echo "- $lines pods starting..."
    sleep 0.5
    lines="$(kubectl get pods -n kube-system -o json | jq '.items[].status.phase | select(. != "Running")' | wc -l)"
    kubectl get pods -n kube-system -o json | jq '.items[].status.phase'
done