[package]
name = "auth-operator"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_kube = { path="../../lib/auth-kube" }
auth_client = { path="../../lib/auth-client" }
tokio = { version = "1.0.1", features = ["full"] }
anyhow = "1.0.37"
log = "0.4.11"
env_logger = "0.8.2"