apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authusers.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                display:
                  type: string
                email:
                  type: string
              required: [ display, email ]
            status:
              type: object
              properties:
                invited:
                  type: boolean
                  default: false
                member:
                  type: boolean
                  default: false
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Display
        type: string
        description: The user display name
        jsonPath: .spec.display
      - name: Email
        type: string
        description: The user email
        jsonPath: .spec.email
      - name: Invited
        type: boolean
        description: True if an invite token exists
        jsonPath: .status.invited
      - name: Member
        type: boolean
        description: True if user has provided a password
        jsonPath: .status.member
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: authusers
    singular: authuser
    kind: AuthUser