apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authusers.ponglehub.co.uk
spec:
  group: ponglehub.co.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                display:
                  type: string
                email:
                  type: string
                inviteToken:
                  type: string
                passwordHash:
                  type: string
              required: [ display, email ]
      additionalPrinterColumns:
      - name: Display
        type: string
        description: The user display name
        jsonPath: .spec.display
      - name: Email
        type: string
        description: The user email
        jsonPath: .spec.email
      - name: Invite
        type: string
        description: Has a value if an invite is pending
        jsonPath: .spec.inviteToken
      - name: Password
        type: string
        description: Hashed password
        jsonPath: .spec.passwordHash
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: authusers
    singular: authuser
    kind: AuthUser