# permissions for end users to view authusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authuser-viewer-role
rules:
- apiGroups:
  - auth.ponglehub.co.uk
  resources:
  - authusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.ponglehub.co.uk
  resources:
  - authusers/status
  verbs:
  - get
