
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - auth.ponglehub.co.uk
  resources:
  - authusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.ponglehub.co.uk
  resources:
  - authusers/finalizers
  verbs:
  - update
- apiGroups:
  - auth.ponglehub.co.uk
  resources:
  - authusers/status
  verbs:
  - get
  - patch
  - update
