cluster:
    LOCALLY

    RUN docker-compose \
      -f ../../libraries/images/kube/cluster-compose.yaml \
      up -d

stop:
    LOCALLY

    RUN docker-compose \
      -f ../../libraries/images/kube/cluster-compose.yaml \
      down \
      && rm -rf .scratch

test:
  FROM ../../libraries/images/kube+image

  COPY ../../helm/tests+chart/chart ./test-chart

  WITH DOCKER --compose cluster-compose.yaml
    RUN wait-for-cluster && kubectl get ns
  END