FROM rust:slim
WORKDIR /home/rust/src

RUN apt update && apt install libssl-dev pkgconf -y \
    && rm -rf /var/lib/apt/lists/*

install-chef:
    RUN cargo install --debug cargo-chef

planner:
    FROM +install-chef
    COPY --dir bin lib Cargo.lock Cargo.toml .
    RUN cargo chef prepare
    SAVE ARTIFACT recipe.json

cacher:
    FROM +install-chef
    COPY +planner/recipe.json recipe.json
    RUN cargo chef cook

    SAVE ARTIFACT target
    SAVE ARTIFACT /usr/local/cargo cargo_home

builder:
    COPY --dir bin lib Cargo.lock Cargo.toml .
    COPY +cacher/cargo_home /usr/local/cargo
    COPY +cacher/target ./target
    RUN cargo build

    SAVE ARTIFACT target/debug/auth-operator auth-operator
    SAVE ARTIFACT target/debug/mock mock

runtime:
    FROM debian:buster-slim

    RUN apt update && apt install libssl-dev pkgconf -y \
        && rm -rf /var/lib/apt/lists/*

docker:
    FROM +runtime

    COPY +builder/auth-operator /bin/auth-operator

    ENTRYPOINT [ "/bin/auth-operator" ]

    SAVE IMAGE auth-operator

mock:
    FROM +runtime

    COPY +builder/mock /bin/mock

    ENTRYPOINT [ "/bin/mock" ]

    SAVE IMAGE mock

cluster:
    LOCALLY

    RUN k3d cluster create auth-operator \
      --registry-create \
      --k3s-server-arg "--no-deploy=traefik" \
      --kubeconfig-update-default=false \
      -p "80:80@loadbalancer" \
      --wait

    RUN mkdir -p .scratch \
        && k3d kubeconfig get auth-operator > .scratch/kubeconfig \
        && KUBECONFIG=.scratch/kubeconfig kubectl config use-context k3d-auth-operator

stop:
    LOCALLY

    RUN k3d cluster delete auth-operator \
        && rm -rf .scratch
