build:
    FROM ekidd/rust-musl-builder

    WORKDIR /home/rust/src

    COPY . .

    RUN --mount=type=cache,target=/home/rust/.cargo/git \
        --mount=type=cache,target=/home/rust/.cargo/registry \
        --mount=type=cache,target=/home/rust/src/target \
        sudo chown -R rust:rust /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target && \
        rm -rf ./target/x86_64-unknown-linux-musl/debug/deps/auth_operator* && \
        cargo build && \
        cp ./target/x86_64-unknown-linux-musl/debug/auth-operator auth-operator

    SAVE ARTIFACT auth-operator 

docker:
    FROM scratch

    COPY +build/auth-operator /bin/auth-operator

    ENTRYPOINT [ "/bin/auth-operator" ]

    SAVE IMAGE auth-operator

cluster:
    LOCALLY

    RUN k3d cluster create auth-operator \
      --registry-create \
      --k3s-server-arg "--no-deploy=traefik" \
      --kubeconfig-update-default=false \
      -p "80:80@loadbalancer" \
      --wait

    RUN mkdir -p .scratch \
        && k3d kubeconfig get auth-operator > .scratch/kubeconfig \
        && KUBECONFIG=.scratch/kubeconfig kubectl config use-context k3d-auth-operator

stop:
    LOCALLY

    RUN k3d cluster delete auth-operator \
        && rm -rf .scratch
