start:
    just ../../start

stop:
    just ../../stop

build:
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
        go build -v -o dist/event-responder ./main.go

image IMAGE_TAG: build
    DOCKER_BUILDKIT=1 docker build \
        -f ../../docker/go.Dockerfile \
        -t {{IMAGE_TAG}} \
        --build-arg EXECUTABLE=event-responder \
        ./dist

int-test:
    go test -v --count 1 ./integration