FROM ../../libraries/images/golang+image

deps:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY --dir internal pkg .

build:
  FROM +deps

  RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o db-init ./cmd/db-init/main.go

  SAVE ARTIFACT db-init

image:
  FROM scratch

  COPY +build/db-init /go/bin/db-init
  ENTRYPOINT [ "/go/bin/db-init" ]

  SAVE IMAGE db-init

test:
  FROM +deps

  COPY docker-compose.yaml docker-compose.yaml

  WITH DOCKER --compose docker-compose.yaml
    RUN CGO_ENABLED=0 \
      GOOS=linux \
      GOARCH=amd64 \
      DB_HOST=localhost \
      DB_USER=root \
      go test ./cmd/...
  END

module:
  FROM +deps

  SAVE ARTIFACT ./*