FROM ../../libraries/images/golang+image

deps:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY --dir internal pkg .

test:
  FROM +deps
  BUILD +db

  ARG DB_HOST
  RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 \
      GOOS=linux \
      GOARCH=amd64 \
      DB_HOST=$DB_HOST \
      DB_USER=root \
      go test -v ./pkg/...

db:
  LOCALLY
  RUN if ! docker ps | grep -q cockroachdb; then \
        docker run --rm -d --name cockroachdb cockroachdb/cockroach:v20.2.8 start-single-node --insecure; \
        direnv reload; \
      fi

db-stop:
  LOCALLY
  RUN docker stop cockroachdb || true

module:
  FROM +deps

  SAVE ARTIFACT ./*