FROM ../../libraries/images/golang+image

deps:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY --dir internal pkg .

test:
  FROM +deps

  COPY docker-compose.yaml docker-compose.yaml

  WITH DOCKER --compose docker-compose.yaml
    RUN CGO_ENABLED=0 \
      GOOS=linux \
      GOARCH=amd64 \
      DB_HOST=localhost \
      DB_USER=root \
      go test -v ./pkg/...
  END

db-test:
  RUN --no-cache cat /etc/resolv.conf

db:
  LOCALLY

  RUN docker network create db-net 
  RUN docker run --rm -d --name cockroachdb cockroachdb/cockroach:v20.2.8 start-single-node --insecure
  RUN docker network connect db-net cockroachdb
  RUN docker network connect db-net earthly-buildkitd

module:
  FROM +deps

  SAVE ARTIFACT ./*