---
# Source: templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
    name: operators
---
# Source: templates/app.servers.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-operator
  namespace: operators
automountServiceAccountToken: true
---
# Source: templates/app.servers.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db-operator
rules:
- apiGroups:
  - ponglehub.co.uk
  - apps
  - ''
  resources:
  - cockroachdbs
  - cockroachdbs/status
  - cockroachclients
  - cockroachclients/status
  - statefulsets
  - secrets
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
# Source: templates/app.servers.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: db-operator
subjects:
- kind: ServiceAccount
  name: db-operator
  namespace: operators
---
# Source: templates/app.servers.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-operator
  name: db-operator
  namespace: operators
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: db-operator
  type: ClusterIP
---
# Source: templates/app.servers.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-operator
  name: db-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-operator
  template:
    metadata:
      labels:
        app: db-operator
    spec:
      serviceAccountName: db-operator
      containers:
      - name: server
        image: k3d-pongle-registry.localhost:5000/db-operator
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
