{{- if .Values.linkerd2.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: ssl-secret
  namespace: linkerd
data:
  tls.key: {{ .Values.secrets.ssl.key | b64enc }}
  tls.crt: {{ .Values.secrets.ssl.crt | b64enc }}
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: linkerd
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:linkerd-web.linkerd.svc.cluster.local:8084
spec:
  rules:
    - host: {{ .Values.linkerd2.ingress.hostname }}
      http:
        paths:
          - backend:
              serviceName: linkerd-web
              servicePort: 8084
  tls:
  - hosts:
    - {{ .Values.linkerd2.ingress.hostname }}
    secretName: ssl-secret
{{- end -}}