servers:
  app:
    enabled: false
    # image:

functions: {}
# functions:
#   app:
#     enabled: false

test:
  name: test
#   image:
  service: true

cockroach:
  enabled: false
  statefulset:
    replicas: 1

migrations:
  enabled: false
  name: migrations
  # baseImage:
  flywayImage: docker.io/flyway/flyway:7

  db:
    # host:
    port: 26257
  
  sets:
  # - user:
  #   database:
  #   migrations: