FROM ../../../../libraries/images/node+image
WORKDIR /src

deps:
  COPY ../../../../libraries/node/eslint-config-ponglehub+publish/marker /markers/1
  COPY ../../../../libraries/node/async+publish/marker /markers/2

  COPY package*.json ./
  RUN npm install

  SAVE ARTIFACT package.json AS LOCAL ./package.json
  SAVE ARTIFACT package-lock.json AS LOCAL ./package-lock.json
  
  COPY ./.eslintrc ./.eslintrc
  COPY --dir tests helpers .

lint:
  FROM +deps
  RUN npm run lint

docker:
  FROM +deps

  ENTRYPOINT [ "npm" ]
  CMD [ "run", "int-test" ]

  COPY ../../../test-chart+publish/marker /markers/3

  SAVE IMAGE auth-server-tests

all:
  BUILD +lint
  BUILD +docker