apiVersion: v2
name: ponglehub-infra
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

dependencies:
  - name: prometheus
    version: ~11.1.5
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
  - name: grafana
    version: ~5.0.23
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled
  - name: loki-stack
    repository: https://grafana.github.io/loki/charts
    version: "*"
    condition: loki-stack.enabled
  - name: verdaccio
    version: 0.10.0
    repository: https://charts.verdaccio.org
    condition: verdaccio.enabled
  - name: linkerd2
    version: "2.8.1"
    repository: https://helm.linkerd.io/stable
    condition: linkerd2.enabled
  - name: strimzi-kafka-operator
    version: "*"
    repository: https://strimzi.io/charts/
    condition: strimzi-kafka-operator.enabled