secrets:
  admin:
    username: admin
    # password:

loki-stack:
  enabled: true
  promtail:
    pipelineStages:
      - docker: {}
      - regex:
          expression: "level\\=(?P<level>\\w+)"
      - labels:
          level:

grafana:
  admin:
    existingSecret: grafana-creds
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - id: prometheus
        name: Prometheus
        type: prometheus
        url: http://infra-prometheus-server
        access: proxy
        isDefault: true
      - id: loki
        name: Loki
        type: loki
        url: http://infra-loki:3100
        access: proxy
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/auth-type: forward
      ingress.kubernetes.io/auth-url: https://auth.ponglehub.co.uk/auth
      ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    hosts:
    - grafana.ponglehub.co.uk
    tls:
    - hosts:
      - grafana.ponglehub.co.uk

verdaccio:
  ingress:
    enabled: true
    hosts:
    - npm.ponglehub.co.uk
    tls:
    - hosts:
      - npm.ponglehub.co.uk

linkerd2:
  enabled: true
  grafana:
    enabled: false
  ingress:
    hostname: linkerd.ponglehub.co.uk

strimzi-kafka-operator:
  enabled: true