FROM golang:1.16

WORKDIR /src

build:
  COPY go.mod go.sum ./
  RUN go mod download

  COPY *.go ./

  RUN --mount=type=cache,target=/root/.cache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o db-init

  SAVE ARTIFACT db-init

docker:
  FROM scratch

  COPY +build/db-init /go/bin/db-init
  ENTRYPOINT [ "/go/bin/db-init" ]

  SAVE IMAGE db-init