secrets:
  admin:
    username: admin
    # password:
  ssl:
    # key:
    # crt:

loki-stack:
  enabled: true
  promtail:
    pipelineStages:
      - docker: {}
      - regex:
          expression: "level\\=(?P<level>\\w+)"
      - labels:
          level:

prometheus:
  enabled: true
  extraScrapeConfigs: |
    - job_name: 'linkerd'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['linkerd']

      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_container_name
        action: keep
        regex: ^prometheus$

      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - '{job="linkerd-proxy"}'
          - '{job="linkerd-controller"}'

grafana:
  enabled: true
  admin:
    existingSecret: grafana-creds
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - id: prometheus
        name: prometheus
        type: prometheus
        url: http://infra-prometheus-server
        access: proxy
        isDefault: true
      - id: loki
        name: Loki
        type: loki
        url: http://infra-loki:3100
        access: proxy
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/ssl-redirect: "true"
      # ingress.kubernetes.io/auth-type: forward
      # ingress.kubernetes.io/auth-url: https://auth.ponglehub.co.uk/auth
      # ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    hosts:
    - grafana.ponglehub.co.uk
    tls:
    - hosts:
      - grafana.ponglehub.co.uk
      secretName: ssl-secret

verdaccio:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - npm.ponglehub.co.uk
    tls:
    - hosts:
      - npm.ponglehub.co.uk
      secretName: ssl-secret

chartmuseum:
  enabled: true
  env:
    open:
      STORAGE: local
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
  ingress:
    enabled: true
    hosts:
    - name: helm.ponglehub.co.uk
      tls: true
      tlsSecret: ssl-secret

linkerd2:
  enabled: true
  grafana:
    enabled: false
  ingress:
    hostname: linkerd.ponglehub.co.uk
  enforcedHostRegexp: ^linkerd\.ponglehub\.co\.uk$

strimzi-kafka-operator:
  enabled: true